### ISSUE TITLE
terraform: staging-pha environment currently undeployable

### ISSUE THREAD

**Issue by BranLwyd** [abetterinternet/prio-server#1045]
The `staging-pha` environment currently cannot be deployed. (`staging-facil` is confirmed deployable at time of writing.)

The issue encountered appears to be:
* `staging-pha` (intentionally) deploys its k8s cluster into GKE.
* `staging-pha` also specifies `use_aws = true`, with the intent of placing storage in AWS rather than GCP.
* But as of #802, `use_aws` now also causes the k8s cluster to be deployed in AWS.

We should fix the configuration appropriately so that we continue to deploy `staging-pha` as before the changes, i.e. storage in AWS, compute in GCP. An initial attempt to make this change did not work out (probably because it was not comprehensive enough of a change, or perhaps because it was too comprehensive of a change).

**Comment by tgeoghegan** [comment]
This could be addressed by doing #659, in the course of which we would tear down this environment.

**Comment by tgeoghegan** [comment]
Brandon and I agreed to solve this by doing #659, which would entail destroying this environment, so we can close this.
