### ISSUE TITLE
terraform: configure cluster autoscaler for EKS

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#1091]
By default, EKS does not deploy a cluster autoscaler. So even if the cluster is backed by an AWS EC2 autoscaling group, Kubernetes doesn't know how to spawn more worker nodes in the face of high demand for resources. We need to wire up the Terraform gunk to [configure and deploy a cluster autoscaler into EKS](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html).

**Comment by BranLwyd** [comment]
This is a source of manual toil; tagging to allow discussion on our ops-due-diligence pass.

**Comment by tgeoghegan** [comment]
Resolved by #1191
