### ISSUE TITLE
Make `keyRotatorImage` in deploy-controller configurable

### ISSUE THREAD

**Issue by hostirosti** [abetterinternet/prio-server#1112]
Can we make this configurable to allow for independently build images to be used here?

https://github.com/abetterinternet/prio-server/blob/154024874f84b9fc526b5c5352b60a492dbe6917/deploy-operator/controllers/locality_controller.go#L49

**Comment by BranLwyd** [comment]
The in-progress work to enable key rotation will not use the `deploy-operator`, but I will ensure that the docker image is configurable similarly to the `workflow-manager` & `facilitator`:

https://github.com/abetterinternet/prio-server/blob/154024874f84b9fc526b5c5352b60a492dbe6917/terraform/main.tf#L194-L212

**Comment by BranLwyd** [comment]
This is implemented (but not yet deployed to production environments) as https://github.com/abetterinternet/prio-server/blob/f8e9707bb94471e6d9d7abcb9afda3216e652adc/terraform/main.tf#L190-L198.
