### ISSUE TITLE
Enable worker autoscaling in production environments

### ISSUE THREAD

**Issue by BranLwyd** [abetterinternet/prio-server#1169]
Currently, the ability to auto-scale workers based on them falling behind on work is implemented, but the default configuration is that the minimum & maximum number of workers is the same, so no autoscaling actually occurs.

We should update both ISRG & NIH deployments to allow worker autoscaling to actually occur.

**Comment by tgeoghegan** [comment]
Out of an abundance of caution, we should enable this in staging environments first (crucially `staging-facil` on GCP and `staging-intl` on AWS) and roll it out to prod once we see it working well in staging.

**Comment by tgeoghegan** [comment]
Deployed to `staging-facil` and `staging-pha` in #1194.

**Comment by tgeoghegan** [comment]
This got deployed to prod-us yesterday, but is not yet in prod-intl, so reopening.

**Comment by BranLwyd** [comment]
Deployed to `prod-intl` as of yesterday afternoon; closing.
