### ISSUE TITLE
Move Avro schema into own repository

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#12]
We store the JSON Avro schema files alongside the Rust implementation here in prio-server. @yuriks points out that this means we have to rev the implementation in lockstep with the schema. This would be easier if the schema was pulled in as a versioned dependency, and it would also be better for other projects wanting to consume the schemas.

**Comment by tgeoghegan** [comment]
This doesn't block anything for any reason I can think of, so no milestone. Further there's a few ways to shave this yak: git submodule, Rust crate, etc.

**Comment by tlepoint** [comment]
+1

**Comment by tgeoghegan** [comment]
The format of these messages are not likely to change, so I don't think there's a lot of value in addressing this.
