### ISSUE TITLE
Comments on docs/debugging.md

### ISSUE THREAD

**Issue by hostirosti** [abetterinternet/prio-server#1266]
This is a running list of discoveries for debugging a prio server container, will format later.

Following [docs/debugging.md](docs/debugging.md) to get to the container `pid` using `ctr` did not work for me, here is what I did instead:

### Finding container to debug and taking core dump.

ctr doesn't always show the image name or even the image sha256 you'd expect. If you can't find the container you are looking for use the following steps to discover the right container:

```
ctr -n k8s.io images ls | grep <image-name>
```

Then use the sha256 from your image and see what other sha256's are used for the same image with
```
ctr -n k8s.io images ls | grep <sha256>
```
Note those other sha256's down to filter the container id list

Run the following with sha256's from above discovery:
```
ctr -n k8s.io containers ls | grep <sha256> 
```

Go through the list of above container ids until you find the right pod name you're looking for:

```
ctr -n k8s.io containers info <container-id> | grep name
```

Once the right container is found grep the `io.kubernetes.cri.sandbox-id`
```
ctr -n k8s.io containers info <container-id> | grep id
```

To find the `pid` do:
```
ps aux | grep <io.kubernetes.cri.sandbox-id-value>
```

To find the child process of the shim do:
```
ps --ppid <above found pid>
```

**Comment by tgeoghegan** [comment]
Thanks, this is good stuff! I've been experimenting a bit and I've also found that `ctr containers list` takes a `filter` argument that lets you query on attributes of a container. For instance, given a Kubernetes pod name, I was able to do this:

`ctr -n k8s.io containers list labels."io.kubernetes.pod.name"==intake-batch-apple-548846d9d6-tpml6`

I'll incorporate these tips into the documentation.
