### ISSUE TITLE
Automated integration/correctness testing

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#226]
We should be able to automatically run end to end integration tests against instances of the application running in a cloud. The ideal would be the ability to run such a test on any PR, but I'd settle for a nightly test run against a staging environment.

**Comment by BranLwyd** [comment]
Per chat with @tgeoghegan today, these tests should include correctness testing; i.e. check that the (generated) ingestion data matches the aggregated output in the environment.

**Comment by tgeoghegan** [comment]
Solving this would entail creating a new deployment whose job it is to reassemble sum parts and verify that the outputs are as expected. Beyond that, we would have to either create a channel between the sample generation task and the sum verification task to allow the former to transmit expected sums to the latter, OR somehow make sample generation deterministic so that the sum verifier can figure out the expected sums without explicit communication.
