### ISSUE TITLE
intake-batch Kubernetes job names must incorporate batch UUID

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#231]
At the moment, intake-batch jobs have names like `i-<truncated aggregation ID>-<date>`, yielding job names like `i-kittens-seen-2020-11-25-01-23`. This causes collisions if multiple batches for a single aggregation arrive in the same minute. The job name needs to include at least some of the batch UUID to ensure uniqueness (or at least give us a better hope of uniqueness). The tricky thing is fitting a unique component as well as some human-readable information in the meager 63 characters that Kubernetes affords us!

**Comment by jsha** [comment]
It would be nice to have a set of "boring" prefixs on aggregation IDs that we always strip. That way if an ingestor prefixes all their aggregation IDs with the same thing, that doesn't need to take up any space in the job name.

**Comment by tgeoghegan** [comment]
Or we could lop off the front of the aggregation name instead of the end, given that the interesting and identifying portions of those strings tend to be at the end and not the front.
