### ISSUE TITLE
Make Prometheus and Alertmanager persistent disks regional

### ISSUE THREAD

**Issue by jsha** [abetterinternet/prio-server#233]
Right now we use the Prometheus Helm chart. That creates GCE persistent disks for Prometheus and Alertmanager. However, those disks are scoped to a zone. We'd rather use regional disks so, when a zone goes down, we can run Prometheus in a different zone in the same region.

**Comment by tgeoghegan** [comment]
Related to #318, both are about overhauling Prometheus storage configuration.
