### ISSUE TITLE
Write some alerting rules

### ISSUE THREAD

**Issue by jsha** [abetterinternet/prio-server#235]
We need to configure some [Prometheus alerting rules](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/).

**Comment by tgeoghegan** [comment]
[We have some rules](https://github.com/abetterinternet/prio-server/blob/main/terraform/modules/monitoring/prometheus_alerting_rules.yml)! I'm sure we'll add more in the future, but those will be tracked by yet-to-be-filed issues tracking specific improvements.
