### ISSUE TITLE
Update terraform to 0.14.0

### ISSUE THREAD

**Issue by aaomidi** [abetterinternet/prio-server#257]
Terraform 0.14.0 was just released at the time of filing this issue. I've pinned the terraform formatter to 0.13.5, but we should look into moving to 0.14.0 and maybe using the new features it provides.

New 0.14.0 stuffs: https://learn.hashicorp.com/collections/terraform/0-14

I believe https://github.com/abetterinternet/prio-server/pull/249 uses some of the new 0.14 things with version locking providers.

**Comment by tgeoghegan** [comment]
I think we already de facto require >=0.14 because I tainted staging and prod by `apply`ing to them with `terraform 0.14.5`. I think the remaining thing to do here is to update the `required_version` value in the `terraform {}` block in `main.tf`.

**Comment by aaomidi** [comment]
This change also includes the terraform version bump for CI since the changes I had were failing with 0.13.5 https://github.com/abetterinternet/prio-server/pull/322/files#diff-68ba9d12f6f2601fe3c9f7f9d0d02aaea52384559d6d08fae7afc941663fdfcdL80

**Comment by tgeoghegan** [comment]
This appears to be long since done.
