### ISSUE TITLE
manifest linter should reject unknown keys in JSON

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#266]
This ingestor manifest:

```
{
  "format": 1,
  "server-identity": {
    "gcp-service-account-email": "enpa-ingestion-batch-writer@enpa-ingestion-narnia.iam.gserviceaccount.com",
    "google-service-account": "112310747466759665351"
  },
  "batch-signing-public-keys": {
    "projects/enpa-ingestion-narnia/locations/us/keyRings/enpa-signature-key-ring/cryptoKeys/enpa-signature-key/cryptoKeyVersions/1": {
      "public-key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtt7BOz0So/JY4Ml0CT2zxQAtXUDY\nJoiG9A82XI2lA56fIAE8ECkQX5NuRCrk6lx3Tg6biH0GBZMWSfwENa6DQg==\n-----END PUBLIC KEY-----\n",
      "expiration": "20210101T000000Z"
    }
  }
}
```

... is invalid because it has `google-service-account` instead of `gcp-service-account-id`. However, because JSON parsing ignores unexpected keys, and `gpp-service-account-id` is optional, it doesn't raise an error.

**Comment by bmw** [comment]
We should continue to not error on unknown keys outside of linting right? If we're fine erroring all the time, this is trivial with [`#[serde(deny_unknown_fields)]`](https://serde.rs/container-attrs.html#deny_unknown_fields), but I'd have to do some more digging to figure out how to do this conditionally.

**Comment by tgeoghegan** [comment]
I think we should always reject unexpected keys. The format for manifests is versioned so I don't think we need to be particularly permissive in parsing (i.e., we don't aim to be backward or forward compatible). Plus, the issue description contains an example of a manifest where the author _meant_ to use `gcp-service-account-id` instead of `google-service-account`, and the error would have been more obvious if we'd rejected the unexpected key.
