### ISSUE TITLE
terraform: support multiple ingestor GCP service accounts

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#327]
Ingestors need to be able to advertise more than one GCP service account email from their manifests. We will need to amend the schema for the ingestor global and specific manifests so that multiple GCP identities can be advertised, and then have Terraform grant write access on ingestion buckets to multiple GCP SAs. I think something like this should work

```
{
  // bump format
  "format": 2,
  "server-identity": {
    // aws-iam-entities only present in Apple manifests
    "aws-iam-entities": [
      { "arn": "arn:aws:iam::00000000:role/somerole" }
    ],
    "gcp-iam-entities": [
      {
        "service-account-email": "someserviceaccount@some-gcp-project.iam.gserviceaccount.com",
        // service-account-id only present in Google manifests
        "service-account-id": "111111111111"
      }
    ]
  },
  "batch-signing-public-keys": {
    "key-id-1": {
      "public-key": "-----BEGIN PUBLIC KEY-----\nPEMPEMPEM\n-----END PUBLIC KEY-----\n",
      "expiration": "20211231T000000Z"
    }
  }
}
```

**Comment by tgeoghegan** [comment]
The tricky thing is that facilitators read the ingestor manifest at the top of each task, and so we have to make a migration plan. I think what would need to happen is:
- Make changes to facilitator so it can parse either format = 1 or format = 2 ingestor manifest
- NCI and ISRG deploy new facilitator
- Apple deploys manifests in new format (Google could too, if they feel like it, or we could support format = 1 indefinitely)
- NCI and ISRG `terraform apply` to pick up new manifests and amend policies accordingly

**Comment by winstrom** [comment]
I'm going to track down if I can do better password rolling on our end before forcing this migration.

**Comment by tgeoghegan** [comment]
We clearly didn't wind up needing to do this, so closing.
