### ISSUE TITLE
GitHub actions: push-deploy-operator and push-manifest-updater failing

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#361]
The GitHub actions for pushing the `deploy-operator` and `manifest-updater` containers to DockerHub when we cut a release fail: https://github.com/abetterinternet/prio-server/actions/runs/548772488

I think this is because the `isrgautomaton` user that we use to talk to DockerHub is not permitted to push to those repositories on DockerHub, but maybe the repo needs to be created manually.

**Comment by aaomidi** [comment]
I've removed these from the automated build since they're not currently used.
