### ISSUE TITLE
Implement retries in S3 requests

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#41]
As a workaround for a mismatch between connection pool timeouts in Hyper and AWS S3, #36 carefully constructs HTTP clients with a carefully chosen timeout value. For more robustness, we should implement retries.

**Comment by yuriks** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorBestPractices.html

**Comment by tgeoghegan** [comment]
#260 is progress towards this, but I'm leaving this open because that PR only handles HTTP dispatch errors. We should have more comprehensive error handling as described in Amazon docs, and should also do exponential backoff.

**Comment by tgeoghegan** [comment]
More good material on AWS retry best practices: https://github.com/rusoto/rusoto/issues/234#issuecomment-395534542
