### ISSUE TITLE
Sum part message should include the number of shares that are included in the sum part

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#43]
In order to de-bias the final data, we need to include the total number of shares that are included in the sum part. We will have to extend the `PrioSumPart` message to include a field for this and have the reduce step(s) record the value.

**Comment by yuriks** [comment]
Using slightly stricter terminology:

We want the number of individual clients (or equivalently, unique packet UUIDs) that are present in a batch. This is not always corresponding exactly to the number of shares:
 - For aggregating a batch into a sum, each batch will have unique UUIDs on each packet, so the count for that is the number of input packets
 - For aggregating together multiple batch sums into a time-range sum, each batch would've presumably had unique UUIDs, so the count of that aggregation is the sum of the counts of the inputs.
 - However, for summing together multiple sums, to reconstruct the final clear-text aggregation, *each input is assumed to descend from the same set of UUIDs*, and therefore *the count is the same as the count of the inputs* (which have to all match for the operation to be valid).

**Comment by aaomidi** [comment]
Just to see if I'm understanding this correctly, we want to include a field like 

```avsc
        {
            "name": "total_individual_clients",
            "type": "long",
            "doc": "The total number of total individual clients included in the sum."
        }
```

Inside sum-part.

And beyond that we want to include that value inside `SumPart`, from what @yuriks wrote it's not safe for me to get the number of total_shares() on the server and use the legnth of that right? 

e.g.

```
        let total_indivudal_clients = server
            .total_shares().len() as i64;
```

This isn't necessarily valid from what I'm understanding?

Does that mean for this change I'll have to make changes to https://github.com/abetterinternet/libprio-rs/blob/main/src/server.rs to contain a field that has the running total of the number of individual clients?
