### ISSUE TITLE
Figure out secrets backups in AWS secret storage

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#661]
`deploy-tool` supports backing up Kubernetes secrets into GCP Secret Manager for disaster recovery. We should also teach it to back up secrets into the equivalent Amazon product.

**Comment by BranLwyd** [comment]
Plan of record:
* `key-rotator` will be responsible for backups, rather than `deploy-tool`.
* Backup will be automated.
* Implementation must be able to backup keys to both GCP & AWS' secret stores.

**Comment by tgeoghegan** [comment]
`key-rotator` on `main` appears to be capable of backing up keys to AWS. What's left here, @BranLwyd? Just deploying this change to `prod-intl`?

**Comment by BranLwyd** [comment]
I was waiting for `deploy-tool` to be gone, but now that that's happened it's just deploying to `prod-intl`. I have one final PR I'd like to make it into a release & then I'll deploy & close this bug.

**Comment by BranLwyd** [comment]
`prod-intl` was deployed to yesterday with a `key-rotator` capable of backing up keys; closing this bug.
