### ISSUE TITLE
Move the manifests (global, etc) to be deployed using terraform

### ISSUE THREAD

**Issue by aaomidi** [abetterinternet/prio-server#71]
Right now we have some statically deployed manifest files - we should make these get deployed using GCP.

**Comment by tgeoghegan** [comment]
I'm not sure I understand this. Are you talking about content like https://portcull.is/ingestor-1/global-manifest.json and https://portcull.is/pha-servers/global-manifest.json? I should have explained those: that's just handmade content I put up there so I could test consumption of manifests in Terraform. In a real deploy, those would be served from completely different domains.
