### ISSUE TITLE
dependabot vs task-replayer

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#719]
[`task-replayer` pulls in a module from `workflow-manager`](https://github.com/abetterinternet/prio-server/blob/main/task-replayer/go.mod).

When dependabot updates dependencies in `workflow-manager`, that breaks `task-replayer/go.sum` and causes [build failures](https://github.com/abetterinternet/prio-server/pull/717)

The dependabot PRs can generally be fixed by checking them out locally, and then `cd task-replayer && go mod download whatever/module/was/updated && go mod tidy` then force pushing the changes back onto the dependabot PR branch. However this is a chore and is especially bad when there are multiple dependabot PRs in flight because force pushing onto a branch makes it impossible for dependabot to rebase that branch.

We should see if there's a way to make dependabot aware of the cross module dependency, or if I did something wrong in either go.mod.

**Comment by tgeoghegan** [comment]
This makes managing dependabot PRs a real chore, so tagging ops-due-diligence because we could claw back some time by cleaning this up.

**Comment by BranLwyd** [comment]
https://github.com/abetterinternet/prio-server/pull/1166 removed task-replayer entirely, which is certainly one way of resolving this issue.
