### ISSUE TITLE
Make `encryption_key_id` optional in `PrioDataSharePacket`

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#73]
@winstrom informs me that Apple's ingestion server will not be populating the `encryption_key_id` field in `PrioDataSharePacket` messages at first. This means:

* We must make that field optional in the Avro schema so it can be safely omitted by Apple
* Data share processors will not be able to rely on its presence, meaning that for each packet, they may have to try all the packet decryption keys they have available to them in the k8s secret store

**Comment by tgeoghegan** [comment]
Fixed by #81

**Comment by divergentdave** [comment]
For posterity, `encryption_key_id` from Apple ingestion servers is currently set to the empty string, not null.
