### ISSUE TITLE
`terraform`: move to Terraform >=1.0

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#784]
`terraform/main.tf`'s `terraform{}` block currently mandates `required_version = ">= 0.14.4"`, but our distinguished colleagues at HashiCorp [shipped Terraform 1.0](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability) back in June. We should move forward to that, dealing with any incompatibilities.

`terraform apply` can "taint" TF state with the version of Terraform that was used, so we should also take the opportunity to refine our `terraform{}` block so that (if possible) it sets a maximum Terraform version.

**Comment by tgeoghegan** [comment]
@ezekiel ran into some problems with Terraform trying to use the GCP Cloud Resource Management API, which I suspect are related to TF 1.0, and he volunteered to get into this.

Besides changing required versons in `terraform/main.tf`, we likely also need to update `.github/workflows/ci-build.yml` so that the TF linter job uses the newer TF.

**Comment by aaomidi** [comment]
FWIW terraform 1.0 should be essentially the same as terraform 0.15.x

**Comment by tgeoghegan** [comment]
[PR on `isrg-cloud-bootstrap`](https://github.com/abetterinternet/isrg-cloud-bootstrap/pull/5)
[PR on `prio-server`](https://github.com/abetterinternet/prio-server/pull/1296)

With these changes, I was able to `make plan`, `make plan-cluster-bootstrap`, `make apply-cluster-bootstrap` and `make apply` to my devenv without issues.

Once we merge these changes, each env will get migrated to TF 1.1 as they get applied by Terraform.
