### ISSUE TITLE
Place entire cert chain in specific manifest when certifying packet encryption keys

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#83]
Per https://docs.google.com/document/d/1eKIXOVK6W8AsSnoisw26R1rpKtPBf0rnjn9kSSEC3PE/edit?disco=AAAAHJj4NAg, Apple needs the whole cert chain given to them, not just the leaf. The ACME protocol exposes an endpoint for this, so this should be possible, but we have to figure out how to get it from CertMagic.

**Comment by tgeoghegan** [comment]
[ACMEManager.Issue](https://pkg.go.dev/github.com/caddyserver/certmagic#ACMEManager.Issue) returns `IssuedCertificate`, which at a glance only wraps the leaf cert. CertMagic definitely gets the [whole cert chain in memory](https://github.com/caddyserver/certmagic/blob/81657a23377cad89ed4c08d3741b40b3cda055c5/acmemanager.go#L299) so we could plumb it up via API, or maybe we can hit the ACME endpoint for the cert chain ourselves.

**Comment by mholt** [comment]
I actually think it does return the whole cert chain in PEM format. It has to in order for CertMagic to store the whole chain in storage.

**Comment by tgeoghegan** [comment]
I was definitely wrong that we only get the leaf. However, It seems that what we get is the leaf and the intermediate, but not the root. Here's [a sample manifest](https://demo-gcp.manifests.isrg-prio.org/test-pha-1-ingestor-1-manifest.json) I generated just now:

```
{
    "format": 0,
    "ingestion-bucket": "us-west-1/prio-demo-gcp-test-pha-1-ingestor-1-ingestion",
    "peer-validation-bucket": "us-west-1/prio-demo-gcp-test-pha-1-ingestor-1-peer-validation",
    "batch-signing-public-keys": {
        "demo-gcp-test-pha-1-ingestor-1-batch-signing-key": {
            "public-key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/8OzWHOvmin1KeaiMWFQXfNwS9uZ\n839EjwMff1VB4dnurW38FRP+Z0KxIdvvrPsGMWdPXoTASRAPEHHqpWlTlg==\n-----END PUBLIC KEY-----\n",
            "expiration": "2021-01-21T17:25:06Z"
        }
    },
    "packet-encryption-certificates": {
        "demo-gcp-test-pha-1-ingestion-packet-decryption-key": {
            "certificate": "-----BEGIN CERTIFICATE-----\nMIIEyDCCA7CgAwIBAgISAz839W+73L5MCcvjIcGN5IdJMA0GCSqGSIb3DQEBCwUA\nMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD\nExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDEwMjMxNTI2MTlaFw0y\nMTAxMjExNTI2MTlaMDkxNzA1BgNVBAMTLnRlc3QtcGhhLTEuZGVtby1nY3AuY2Vy\ndGlmaWNhdGVzLmlzcmctcHJpby5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\nAAS2MzXRMydpsuLfU11OcxAEw4TTPXiZQDvHbKLsrb/ltn1BHjBROv4qQ+N42b3q\nd4qpKPID9DQwqkLavJnyNrUHo4ICgjCCAn4wDgYDVR0PAQH/BAQDAgeAMB0GA1Ud\nJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW\nBBTije4mjwh0FYaslgOONkBP8EL6jjAfBgNVHSMEGDAWgBSoSmpjBH3duubRObem\nRWXv86jsoTBvBggrBgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3Nw\nLmludC14My5sZXRzZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0\nLmludC14My5sZXRzZW5jcnlwdC5vcmcvMDkGA1UdEQQyMDCCLnRlc3QtcGhhLTEu\nZGVtby1nY3AuY2VydGlmaWNhdGVzLmlzcmctcHJpby5vcmcwTAYDVR0gBEUwQzAI\nBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nw\ncy5sZXRzZW5jcnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdgBc3EOS\n/uarRUSxXprUVuYQN/vV+kfcoXOUsl7m9scOygAAAXVWSEujAAAEAwBHMEUCIQCy\n7I7IEWjwejkWoXouYpTlTZQEcqJKUEJb4hAylk+coQIgaOA9N5pNXMiUJVB0R9qB\nSZDo9TTel3CB9n8Mw7ob3bEAdQD2XJQv0XcwIhRUGAgwlFaO400TGTO/3wwvIAvM\nTvFk4wAAAXVWSEuhAAAEAwBGMEQCIDDBP7Eprokk8lxPScf8Po3ct6aAmcVK2VKr\n/UM7KaWOAiAOmHTRKFCS1riC3j/QXjKDI72qfMfS+xPCrdSVHVvV5TANBgkqhkiG\n9w0BAQsFAAOCAQEAVi5NKd51DwJExXcim4MH6OwUt3bxIbMkRfmpn/vnWBXMbvDx\nN/sI65/HScz4x0u0HGPzKiHd2ts2/08/sHM/RcvNQ7CcltjZxHuojZv9biYnSJKj\napcHFAkIjCXfzWplqafk/hbwNF3ea2J9hI/R5uj8xkJ/qHpeJVJ5p8hl6fY2kS+y\nW37MDkcIuKSgFFgXm4IOZkhWm6I/3HhiKSVj40t9GJQLiK1+BJXc5Pcrss6XSYJF\nhSTh8X+pzFXgGol5UUCXnrhx8B89cr4CfQvqjPR58ffj/t+GkweZC04ng8VAjNgi\nL4Y6WaBStPSp21Mjpio0zQ0G78/G7MyP5Z4hHg==\n-----END CERTIFICATE-----\n\n-----BEGIN CERTIFICATE-----\nMIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/\nMSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT\nDkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow\nSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT\nGkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF\nq6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8\nSMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0\nZ8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA\na6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj\n/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T\nAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG\nCCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv\nbTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k\nc3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw\nVAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC\nARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz\nMDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu\nY3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF\nAAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo\nuM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/\nwApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu\nX4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG\nPfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6\nKOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==\n-----END CERTIFICATE-----\n"
        }
    }
}
```
The second cert block in there is `Subject: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3`, with `Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3`, but that root certificate isn't in there. @mholt is that consistent with your expectation of what would be returned from [ACMEManager.Issue](https://pkg.go.dev/github.com/caddyserver/certmagic#ACMEManager.Issue)?

@winstrom can you confirm whether Apple needs the entire cert chain all the way back to the root or if leaf+intermediate suffices?

**Comment by mholt** [comment]
It is uncommon to serve the root during a TLS handshake. 🤔

**Comment by winstrom** [comment]
This should be fine -- having the intermediate and the leaf

**Comment by tgeoghegan** [comment]
@mholt I apologize for my tone, I'm not at all surprised that CertMagic is doing the sensible thing for TLS servers! Our use case is extremely unusual. I appreciate your implicit confirmation that this is the expected behaviour.

@winstrom thank you for the confirmation that this meets Apple's needs. It seems like there's no problem here after all, so I am going to close this, once I have updated some of the sample manifest files in the design doc.

**Comment by tgeoghegan** [comment]
Donezo: https://docs.google.com/document/d/1MdfM3QT63ISU70l63bwzTrxr93Z7Tv7EDjLfammzo6Q/edit#heading=h.f7uu5u7i5wfc

**Comment by mholt** [comment]
@tgeoghegan No need to apologize! I was just commenting to make sure all the angles of the issue were documented. I just didn't want to assert that it was expected/correct behavior because I don't fully understand your use case as well as you do.
